### ISSUE TITLE
auto publish?

### ISSUE THREAD

**Issue by asukaminato0721** [kidonng/notion-appimage#3]
auto check the latest version, publish the built Appimage.

**Comment by asukaminato0721** [comment]
this works :)

```yml
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. 
    # High load times include the start of every hour. 
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    # Every 5 minutes.
    # - cron: '*/5 * * * *'
    # At the beginning of every day.
    - cron: "0 0 * * *"
```
